### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [Toddsqui/freedom#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Toddsqui** [comment]
Sent you an email. I believe what you were looking for was the meta tag that I supplied in the email. Could be wrong. Let me know what you think.

**Comment by MarcoMorawec** [comment]
@Toddsqui Why don't you just give it a go, push things up to Heroku and take a look on how things look on your phone :)

One a side note: It's always good practice to keep communication in the same place to avoid confusion. So rather than referencing an email , put the message from the email, straight into the Github comments, so code and discussion it happening in the same place.

**Comment by Toddsqui** [comment]
Check, check, and double check, thanks so much, Marco! I appreciate this.

**Comment by MarcoMorawec** [comment]
:+1: @Toddsqui
