### ISSUE TITLE
Quote Author Names Show up Twice

### ISSUE THREAD

**Issue by MarcoMorawec** [Toddsqui/freedom#2]
When going through the quotes, one can see the name of the author to show up on two places - directly below the quote on the left and the right hand place - see how Ernestine Ulmer shows up twice?

The author name should only show up once. Can you fix that?

![screen shot 2015-05-16 at 1 10 01 pm](https://cloud.githubusercontent.com/assets/1474717/7667175/1669c81c-fbcd-11e4-873d-52e69033860c.png)

**Comment by Toddsqui** [comment]
Problem solved. Easy fix, as it turns out. I was just complaining.

**Comment by MarcoMorawec** [comment]
@toddsqui :+1:

Make sure you close the issue now that you solved it. 

PS. New Quote for your app: "If you want freedom, buy a stranger an ice cream every time you catch yourself complaining" ;)

**Comment by Toddsqui** [comment]
Haha! Got it ;) Thanks!
