### ISSUE TITLE
Align the Top-Nav Links Correctly

### ISSUE THREAD

**Issue by MarcoMorawec** [Toddsqui/freedom#3]
The top nav links for "contribute" and "about" should be pulled more to the right - currently they're stuffed underneath the "knowledge is power" sentence.

Can you fix the alignment of the top-nav links.

![screen shot 2015-05-16 at 1 10 01 pm](https://cloud.githubusercontent.com/assets/1474717/7667182/5cfda4ce-fbcd-11e4-8814-3d01ae2ef198.png)

**Comment by Toddsqui** [comment]
Got it, but it looks different on Heroku. Not sure why that is. I tried to update the database on Heroku by running that rake db command from the cheat sheet, but it didn't do anything.

**Comment by MarcoMorawec** [comment]
@Toddsqui looks a lot better now. 

Since I can't see your local version, I can only go with what I see on Heroku and that looks good.

FYI: running the rake db command is for database migrations (adding columns to your database table(s)), and since this is a CSS issue, running the rake db command won't help.

Make sure you close this issue, now that you solved it.
